In [14]:
import numpy.matlib
import numpy as np

#如果編號相同，其產生的亂數會固定
#0是其編號
np.random.seed(0) 

#A是一個3X3,其內部數值為-5到5之間亂數挑選的矩陣
A = np.random.randint(-5,5,size=(3,3)) 

#B是一個5X5,其內部數值為-5到5之間亂數挑選的矩陣
B = np.random.randint(-5,5,size=(5,5)) 

#C是一個10X10,其內部數值為-5到5之間亂數挑選的矩陣
C = np.random.randint(-5,5,size=(10,10)) 

#如果編號相同，其產生的亂數會固定
#1是其編號
np.random.seed(1) 

#A_v是一個3X1,其內部數值為-5到5之間亂數挑選的矩陣
A_v = np.random.randint(-5,5,size=(3,1)) 

#B_v是一個5X1,其內部數值為-5到5之間亂數挑選的矩陣
B_v = np.random.randint(-5,5,size=(5,1)) 

#C_v是一個10X1,其內部數值為-5到5之間亂數挑選的矩陣
C_v = np.random.randint(-5,5,size=(10,1)) 

In [15]:
#以下程式是在使用A矩陣當作方程式係數，A_v矩陣當作結果，以此計算變數
#換句話說，假設ax+by = c
#A = [a,b], A_v = c, x = [x,y]
x = np.linalg.solve(A, A_v)
y = np.linalg.solve(B, B_v)
z = np.linalg.solve(C, C_v)

In [16]:
print( 
f''' 

A = {A} 

A_v = {A_v} 

x = {x} 

''') 

 

A = [[ 0 -5 -2]
 [-2  2  4]
 [-2  0 -3]] 

A_v = [[0]
 [3]
 [4]] 

x = [[-1.75806452]
 [ 0.06451613]
 [-0.16129032]] 




In [17]:
print( 
f''' 

B = {B} 

B_v = {B_v} 

y = {y} 

''') 

 

B = [[-1  2  1  3  3]
 [-4  1  2  2  3]
 [-4  0  4  3  4]
 [-1 -2 -5 -2  0]
 [-5 -3 -2  3 -4]] 

B_v = [[ 0]
 [-5]
 [-5]
 [-4]
 [ 2]] 

y = [[ 1.14714424]
 [ 0.19167473]
 [-0.03775411]
 [ 1.32913843]
 [-1.06195547]] 




In [18]:
print( 
f''' 

C = {C} 

C_v = {C_v} 

z = {z} 

''') 

 

C = [[-2 -2 -2  2 -5 -4  4  4 -5 -1]
 [ 2 -2 -3  2 -3 -5 -5 -1  0  0]
 [ 1  3 -1 -4 -1  4  3 -4 -4  2]
 [ 4  4 -2  1  2 -3 -5 -2  0  4]
 [-1 -1  1 -1 -1 -2 -1 -1  3 -1]
 [-2  2  0  0 -5 -4  0  4 -2 -5]
 [ 0 -5 -4 -3 -1 -3 -5 -2 -3 -5]
 [ 2  0  4 -5 -3  2 -3  4 -3 -2]
 [-2 -3 -2 -1 -4 -3  4 -4 -1  1]
 [ 3 -3 -2 -5 -5  1 -5  1 -2 -2]] 

C_v = [[ 1]
 [ 4]
 [-3]
 [-1]
 [ 0]
 [-3]
 [-1]
 [-3]
 [-1]
 [ 2]] 

z = [[-11.62300461]
 [  0.26798074]
 [ -1.06367675]
 [  1.09789592]
 [ -2.25909982]
 [  3.58724508]
 [ -6.84901921]
 [  0.69102148]
 [ -1.5110422 ]
 [  5.90293196]] 


