In [1]:
print("I can show you the world")

I can show you the world


In [5]:
print("數字訓練：")

x= 1
y= 2
z= x+y

x,y,z

q = 3.333333333
r = '字串'
s = 987654321 * 1000000

q, r, s

數字訓練：


(3.333333333, '字串', 987654321000000)

In [6]:
A= [[1,2],
    [3,4]]
A

[[1, 2], [3, 4]]

In [21]:
import numpy.matlib
import numpy as np

A= [[1,2],
    [3,4]]
A

[[1, 2], [3, 4]]

In [29]:
array_x = np.array([[1,2,3],[4,5,6],[7,8,9]])

array_x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
array_x * array_x

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [25]:
array_x[0]

array([1, 2, 3])

In [26]:
array_x[0][0]

1

In [27]:
array_x[0][0] * array_x[1][1] * array_x[2][2]

45

In [28]:
for i in range(3):
    print(array_x[0][0])

1
1
1


In [15]:
array_x[0][0]

1

In [16]:
array_x[0][0] * array_x[1][1] * array_x[2][2]

45

In [17]:
for i in range(3):
    print(array_x[0][0])

1
1
1


In [18]:
for i in range(3):
    print(array_x[i][0])

1
4
7


In [19]:
for i in range(3):
    for j in range(3):
        print(array_x[i][j])

1
2
3
4
5
6
7
8
9


In [20]:
z = 0

for i in range(3):
    for j in range(3):
        z += array_x[i][j]
        
z

45

In [21]:
zz = 100

for i in range(3):
    for j in range(3):
        zz -= array_x[i][j]
        
zz

55

In [22]:
zzz = 1

for i in range(3):
    for j in range(3):
        zzz *= array_x[i][j]
        
zzz

362880

In [23]:
zzzz = 9999

for i in range(3):
    for j in range(3):
        zzzz /= array_x[i][j]
        
zzzz

0.02755456349206349

In [32]:
x_det = np.linalg.det(array_x) 

x_det

-9.51619735392994e-16

In [37]:
np.isclose(0, x_det)

True

In [38]:
array_x @ array_x

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])