In [1]:
x = 1
y = 2
z = x+y

x, y, z

(1, 2, 3)

In [2]:
def f(x,y):
    z= x+y
    return z

f(1, 2)

3

In [3]:
def add(x,y):
    z= x+y
    return z
def sub(x,y):
    z= x-y
    return z
def mul(x,y):
    z= x*y
    return z
def div(x,y):
    z= x/y
    return z

a= add(1,2)
s= sub(1,2)
m= mul(1,2)
d= div(1,2)
a,s,m,d

(3, -1, 2, 0.5)

In [4]:
class Number:
    
    def __init__(self,x=0):
        self.x= x
        
    def add(self,y):
        z= self.x + y
        return z
    
    def sub(self,y):
        z= self.x - y
        return z
    
    def mul(self,y):
        z= self.x * y
        return z
    
    def div(self,y):
        z= self.x / y
        return z

n= Number(100)
a= n.add(1)
s= n.sub(1)
m= n.mul(1)
d= n.div(1)
n, n.x, a, s, m, d

(<__main__.Number at 0x257ec46b1f0>, 100, 101, 99, 100, 100.0)

In [5]:
n= Number(100)

In [6]:
class Number:
    
    def __init__(self,x=0):
        self.x= x
        
n= Number(0)

In [7]:
n

In [8]:
class Number:
    
    def __init__(self,x=0):
        self.x= x
        
    def add(self,y):
        z= self.x + y
        return z
    
    def sub(self,y):
        z= self.x - y
        return z
    
    def mul(self,y):
        z= self.x * y
        return z
    
    def div(self,y):
        z= self.x / y
        return z

n= Number(100)
a= n.add(1)
s= n.sub(1)
m= n.mul(1)
d= n.div(1)
n, n.x, a, s, m, d

(<__main__.Number at 0x257ec46b9d0>, 100, 101, 99, 100, 100.0)

In [9]:
class Number(Number):
        
    def __add__(self,y):
        z= self.add(y)
        return z
    def __sub__(self,y):
        z= self.sub(y)
        return z
    def __mul__(self,y):
        z= self.mul(y)
        return z
    def __truediv__(self,y): # 這個除法的名稱比較特殊
        z= self.div(y)
        return z


n= Number(100)
a= n.add(1)
s= n.sub(1)
m= n.mul(1)
d= n.div(1)
n, n.x, a, s, m, d

(<__main__.Number at 0x257ec46bdf0>, 100, 101, 99, 100, 100.0)

In [10]:
a= n.__add__(2)
s= n.__sub__(2)
m= n.__mul__(2)
d= n.__truediv__(2)
n, n.x, a, s, m, d

(<__main__.Number at 0x257ec46bdf0>, 100, 102, 98, 200, 50.0)

In [11]:
a= n+2
s= n-2
m= n*2
d= n/2
n, n.x, a, s, m, d

(<__main__.Number at 0x257ec46bdf0>, 100, 102, 98, 200, 50.0)

In [12]:
x= [1,2,3]
y= [10,20,30]
x+y

[1, 2, 3, 10, 20, 30]

In [1]:
x-y, x*y, x/y

NameError: name 'x' is not defined

In [2]:
class Vector:
    def __init__(self, x):
        self.x= x
        
    def add(self,y):    
        z= [xi+yi for xi,yi in zip(self.x, y)]
        return z

v= Vector([1,2,3,4])
v.add([10,20,30,40])

[11, 22, 33, 44]

In [3]:
class Vector:
    def __init__(self, x):
        self.x= x
        
    def add(self,y):    
        z= [xi+yi for xi,yi in zip(self.x, y)]
        return z
    def sub(self,y):    
        z= [xi-yi for xi,yi in zip(self.x, y)]
        return z
    def mul(self,y):    
        z= [xi*yi for xi,yi in zip(self.x, y)]
        return z
    def div(self,y):    
        z= [xi/yi for xi,yi in zip(self.x, y)]
        return z
    
    def __add__(self,y):    
        z= self.add(y)
        return z
    def __sub__(self,y):    
        z= self.sub(y)
        return z
    def __mul__(self,y):    
        z= self.mul(y)
        return z
    def __truediv__(self,y):    
        z= self.div(y)
        return z

v= Vector([1,2,3,4])
v, v.x

(<__main__.Vector at 0x1dbc6f72190>, [1, 2, 3, 4])

In [5]:
a= v + [10,20,30,40]
s= v - [10,20,30,40]
m= v * [10,20,30,40]
d= v / [10,20,30,40]
v.x, a, s, m, d

([1, 2, 3, 4],
 [11, 22, 33, 44],
 [-9, -18, -27, -36],
 [10, 40, 90, 160],
 [0.1, 0.1, 0.1, 0.1])

In [6]:
import numpy as np

v= [1, 2, 3, 4]
v

[1, 2, 3, 4]

In [7]:
v= np.array(v)
v

array([1, 2, 3, 4])

In [8]:
v.shape

(4,)

In [9]:
A= [[1,2,3,4],
    [5,6,7,8]]
A

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [10]:
A= np.array(A)
A

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
A.shape

(2, 4)

In [12]:
T=[[1,2,3,4],
   [5,6,7,8],
   [9,10,11,12],
   [13,14,15,16]]
T

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

In [13]:
T= np.array(T)
T

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [14]:
T.shape

(4, 4)

In [15]:
T= T.reshape((2,2,4))
T

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [16]:
T.shape

(2, 2, 4)

In [18]:
T[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
T[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
v.ndim, A.ndim, T.ndim

(1, 2, 3)

In [21]:
T4d= T.reshape(2,2,2,2)
T4d

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [22]:
T4d.shape

(2, 2, 2, 2)

In [23]:
v, A, T, T4d

(array([1, 2, 3, 4]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],
 
        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]]]),
 array([[[[ 1,  2],
          [ 3,  4]],
 
         [[ 5,  6],
          [ 7,  8]]],
 
 
        [[[ 9, 10],
          [11, 12]],
 
         [[13, 14],
          [15, 16]]]]))

In [24]:
v

array([1, 2, 3, 4])

In [25]:
v14= v.reshape(1,4)
v14

array([[1, 2, 3, 4]])

In [26]:
v41= v.reshape(4,1)
v41

array([[1],
       [2],
       [3],
       [4]])

In [27]:
v.shape, v14.shape, v41.shape

((4,), (1, 4), (4, 1))

In [28]:
print("I can show you the world")

I can show you the world


In [29]:
print("數字訓練：")

x= 1
y= 2
z= x+y

x,y,z

q = 3.333333333
r = '字串'
s = 987654321 * 1000000

q, r, s

數字訓練：


(3.333333333, '字串', 987654321000000)

In [30]:
import numpy as np

array_x = np.array([[1,2,3],[4,5,6],[7,8,9]])

array_x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
array_x * array_x

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [32]:
array_x[0]

array([1, 2, 3])

In [33]:
array_x[0][0]

1

In [34]:
array_x[0][0] * array_x[1][1] * array_x[2][2]

45

In [35]:
for i in range(3):
    print(array_x[0][0])

1
1
1


In [36]:
for i in range(3):
    print(array_x[i][0])

1
4
7


In [37]:
for i in range(3):
    for j in range(3):
        print(array_x[i][j])

1
2
3
4
5
6
7
8
9


In [38]:
z = 0

for i in range(3):
    for j in range(3):
        z += array_x[i][j]
        
z

45

In [39]:
zz = 100

for i in range(3):
    for j in range(3):
        zz -= array_x[i][j]
        
zz

55

In [40]:
zzz = 1

for i in range(3):
    for j in range(3):
        zzz *= array_x[i][j]
        
zzz

362880

In [41]:
zzzz = 9999

for i in range(3):
    for j in range(3):
        zzzz /= array_x[i][j]
        
zzzz

0.02755456349206349